-- Crear esquema
CREATE SCHEMA IF NOT EXISTS DEMO;

-- Crear tabla de ejemplo
CREATE OR REPLACE TABLE DEMO.CUSTOMERS (
    CUSTOMER_ID NUMBER AUTOINCREMENT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Crear tabla de órdenes
CREATE OR REPLACE TABLE DEMO.ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    ORDER_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TOTAL_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(20)
);

-- Crear vista de ejemplo
CREATE OR REPLACE VIEW DEMO.CUSTOMER_ORDERS AS
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    COUNT(o.ORDER_ID) as TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_SPENT
FROM DEMO.CUSTOMERS c
LEFT JOIN DEMO.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME; 